// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace Microsoft.Maui.Platform.Linux.Services;

public enum AccessibleRole
{
    Unknown,
    Window,
    Application,
    Panel,
    Frame,
    Button,
    CheckBox,
    RadioButton,
    ComboBox,
    Entry,
    Label,
    List,
    ListItem,
    Menu,
    MenuBar,
    MenuItem,
    ScrollBar,
    Slider,
    SpinButton,
    StatusBar,
    Tab,
    TabPanel,
    Text,
    ToggleButton,
    ToolBar,
    ToolTip,
    Tree,
    TreeItem,
    Image,
    ProgressBar,
    Separator,
    Link,
    Table,
    TableCell,
    TableRow,
    TableColumnHeader,
    TableRowHeader,
    PageTab,
    PageTabList,
    Dialog,
    Alert,
    Filler,
    Icon,
    Canvas
}
